#CQ2.1 — Which ekphrastic instances are represented as intermedial objects in the knowledge base?

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geko: <https://w3id.org/geko/#>

SELECT DISTINCT ?ekph ?ekphType
WHERE {
  ?ekph rdf:type ?ekphType .
  ?ekphType rdfs:subClassOf* geko:Ekphrasis .
}
ORDER BY ?ekphType ?ekph