# CQ2.2 — For each ekphrasis, who is the author of the textual expression in which the ekphrastic passage occurs?

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geko: <https://w3id.org/geko/#>

SELECT DISTINCT ?ekph ?author
WHERE {
  ?ekph rdf:type ?t ;
        geko:hasAuthor ?author .
  ?t rdfs:subClassOf* geko:Ekphrasis .
}
ORDER BY ?ekph